name: todo_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  get: ^4.6.5
  internet_connection_checker:
  get_it:
  intl:
  shared_preferences:
  fpdart: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.2
  permission_handler: ^11.3.0
  image: ^4.1.7
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  js: ^0.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
